version: "3"
services:
  nodejs:
    build: docker/node
    tty: true
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "8080:3000"
    working_dir: /usr/src/app

  express:
    build: docker/node
    tty: true
    volumes:
      - ./express:/usr/src/app
    ports:
      - "8081:3000"
    working_dir: /usr/src/app
    command: [ bash, -c, "npm install && npm start" ]